---
- name: Bootstrap
  hosts: localhost
  become: true
  ignore_unreachable: false
  vars_files:
    - inventory/group_vars/vault.yaml
  roles:
    - role: updates
    - role: bootstrap
    - role: firewalld
      when: ansible_os_family == 'RedHat' and 'firewalld.service' in ansible_facts.services
    - role: ssh
      when: ansible_play_hosts | length > 1
    - role: keepalived
      when: enable_keepalived
    - role: unbound
      when: enable_unbound
    - role: pihole
    - role: gravity_sync
      when: enable_gravity_sync
    - role: pihole_updatelists
      when: enable_pihole_updatelists
    - role: status
